config/routes.rb
Rails.application.routes.draw do
  
  resources :substitution_types

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        
  }      
  resources :microposts

  resources :users
  
  resources :categories
  
  resources :comments
  
  resources :substitutions
  
  resources :substitution_types
  
  get "/new_comment_partial/:id " => "microposts#new_comment_partial", :as => 'new_comment_partial' 

  root 'microposts#index'

end

app/controllers/substitution_types_controller.rb
class SubstitutionTypesController < ApplicationController
  before_action :set_substitution_type, only: [:show, :edit, :update, :destroy]

  # GET /substitution_types
  # GET /substitution_types.json
  def index
    @substitution_types = SubstitutionType.all
  end

  # GET /substitution_types/1
  # GET /substitution_types/1.json
  def show
  end

  # GET /substitution_types/new
  def new
    @substitution_type = SubstitutionType.new
  end

  # GET /substitution_types/1/edit
  def edit
  end

  # POST /substitution_types
  # POST /substitution_types.json
  def create
    @substitution_type = SubstitutionType.new(substitution_type_params)

    respond_to do |format|
      if @substitution_type.save
        format.html { redirect_to @substitution_type, notice: 'Substitution type was successfully created.' }
        format.json { render :show, status: :created, location: @substitution_type }
      else
        format.html { render :new }
        format.json { render json: @substitution_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /substitution_types/1
  # PATCH/PUT /substitution_types/1.json
  def update
    respond_to do |format|
      if @substitution_type.update(substitution_type_params)
        format.html { redirect_to @substitution_type, notice: 'Substitution type was successfully updated.' }
        format.json { render :show, status: :ok, location: @substitution_type }
      else
        format.html { render :edit }
        format.json { render json: @substitution_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /substitution_types/1
  # DELETE /substitution_types/1.json
  def destroy
    @substitution_type.destroy
    respond_to do |format|
      format.html { redirect_to substitution_types_url, notice: 'Substitution type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_substitution_type
      @substitution_type = SubstitutionType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def substitution_type_params
      params.require(:substitution_type).permit(:name)
    end
end

app/helpers/substitution_types_helper.rb
module SubstitutionTypesHelper
end

app/views/substitution_types/_form.html.erb
<%= form_for(@substitution_type) do |f| %>
  <% if @substitution_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@substitution_type.errors.count, "error") %> prohibited this substitution_type from being saved:</h2>

      <ul>
      <% @substitution_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/substitution_types/edit.html.erb
<h1>Editing Substitution Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @substitution_type %> |
<%= link_to 'Back', substitution_types_path %>

app/views/substitution_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Substitution Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @substitution_types.each do |substitution_type| %>
      <tr>
        <td><%= substitution_type.name %></td>
        <td><%= link_to 'Show', substitution_type %></td>
        <td><%= link_to 'Edit', edit_substitution_type_path(substitution_type) %></td>
        <td><%= link_to 'Destroy', substitution_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Substitution type', new_substitution_type_path %>

app/views/substitution_types/new.html.erb
<h1>New Substitution Type</h1>

<%= render 'form' %>

<%= link_to 'Back', substitution_types_path %>

app/views/substitution_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @substitution_type.name %>
</p>

<%= link_to 'Edit', edit_substitution_type_path(@substitution_type) %> |
<%= link_to 'Back', substitution_types_path %>