config/routes.rb
Rails.application.routes.draw do
  
  resources :substitution_types

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        
  }      
  resources :microposts

  resources :users
  
  resources :categories
  
  resources :comments
  
  resources :substitutions
  
  resources :substitution_types
  
  get "/new_comment_partial/:id " => "microposts#new_comment_partial", :as => 'new_comment_partial' 

  root 'microposts#index'

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessor :short_content, :formated_date
  before_create :change_content
  before_update :change_content
  belongs_to :category
  belongs_to :user
  has_many :comments
  validates :content, length: { maximum: 1024 }, presence: true
  validates :name, presence: true
  def change_content
    contenido=" "+self.content+" "
    contenido=contenido.gsub(/(.*)(<br\/>)(.*)/, '\1\3')
    #sustitutions={"Yo"=>"Cabron", "Tu"=>"Wey", "El"=>"Culero", "Nosotros"=>"Bola de weyes", "Ustedes"=>"Ato de culeros", "Ellos"=>"Esos weyes", "Ellas"=>"Perras"}
    contenido_tokens=contenido.split
    contenido_tokens.map!{ |word|
      just_the_word=word.gsub(/[^[:word:]\s]/, '')
      if just_the_word.start_with?(word.upcase)
        starts_with_upper=true
      end
      sub_type_e_word=SubstitutionType.find_by name: "ExactWord"
      subs=Substitution.find_by replace_what:just_the_word, user_id: user.id, substitution_type_id: sub_type_e_word.id
      #subs ? (starts_with_upper ? (subs.replace_with.slice(0,1).capitalize + ( just_the_word.upcase ? subs.replace_with.slice(1..-1).capitalize : subs.replace_with.slice(1..-1)))  : (subs.replace_with.slice(0,1).downcase + ( just_the_word.upcase ? subs.replace_with.slice(1..-1).capitalize : subs.replace_with.slice(1..-1)))) :  word
      #subs ? word["#{just_the_word}"]=subs.replace_with : word
      if subs
        word["#{just_the_word}"]=subs.replace_with
      end
      word
    }
    self.content=contenido_tokens.join(" ") +"<br/>"
  end
  def short_content
    @short_content=self.content[0..140]+"..."
  end  
  def formated_date
    @formated_date=self.created_at.strftime("%d/%m/%Y")
  end  
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]
  before_action :set_comment, only: [:new_comment_partial]
  before_action :authenticate_user!, :except => [:index, :show]
  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
    @users = User.all
    @categories = Category.all
  end

  # GET /new_comment_partial
  def new_comment_partial
    render :partial => "/comments/new"
  end
  
  # GET /microposts/1/edit
  def edit
    @users = User.all
    @categories = Category.all
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)
    @users = User.all
    @categories = Category.all
    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    @users = User.all
    @categories = Category.all
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url, notice: 'Micropost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end
    
    def set_comment
      @comment = Comment.find(params[:id])
    end
      
    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:content, :user_id, :category_id, :name)
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_comment.html.erb
<div class="media">
  <a class="pull-left" href="#">
      <img class="media-object" src="http://placehold.it/64x64" alt="">
  </a>
  <div class="media-body">
    <h4 class="media-heading"><%= comment.user %>
        <small><%= comment.created_at %></small>
    </h4>
    <%= comment.content %>
          <div class="reply">
            <%= link_to "Reply", new_comment_partial_path(comment), :remote => true, :name=>"show_new_comment", :id=>"#{comment.id}" %>
          </div>
          <div class="media" id="comment-reply-<%= comment.id %>">
        
          </div>
    <%= render partial: "comment", collection: comment.nested_comments %>
  </div>
</div>

app/views/microposts/_form.html.erb
<%= form_for @micropost, :html => {:class => 'form'} do |f| %>
  <% if @micropost.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label t(:micropost_name) %>:
    <%= f.text_field :name, :class=>'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label t(:micropost_content) %>:
    <%= f.text_area :content, :class=>'form-control' %>
  </div>
  <%= f.hidden_field :user_id,  :value => current_user.id %>
  <div class="form-group">
    <%= f.label t(:micropost_category) %>:
    <%= collection_select(:micropost, :category_id, @categories, :id, :name, {:prompt => false}, {:class=>'form-control'}) %>
  </div>
  <%= f.submit t(:create_micropost_submit), :class => 'btn btn-primary' %>
<% end %>

app/views/microposts/edit.html.erb
<h1>Editing Micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<div class="jumbotron">
  <h1><%= t :home_title %></h1>
  <p><%= t :home_message %></p> 
</div>
<p id="notice"><%= notice %></p>
<div class="row">
    <% @microposts.each do |micropost| %>
    <div class="col-sm-4">
      <h3><%= micropost.name %></h3>
      <p><%= raw micropost.short_content %></p>
      <p><%= link_to micropost.user, user_path(micropost.user) %> | <% if micropost.category %><%= link_to micropost.category, category_path(micropost.category) %><% end %> | <%= link_to t(:show), micropost %> | <%= link_to t(:edit), edit_micropost_path(micropost) %> | <%= link_to t(:delete), micropost, method: :delete, data: { confirm: t(:default_delete_message) } %></p>
    </div>
    <% end %>
</div>
<%= link_to t(:micropost_new_link), new_micropost_path %>

app/views/microposts/new.html.erb
<div class="row">
<h1><%= t(:new_micropost_title) %></h1>
<%= render 'form' %>
</div>
<br/>
<div class="row">
  <%= link_to 'Back', microposts_path %>
</div>

app/views/microposts/show.html.erb
<% content_for :head do %>
<script type="text/javascript">
  $( document ).ready(function() {
      /*$('#new_comment').submit(function() {
          var valuesToSubmit = $(this).serialize();
	  $.ajax({
	      type: "POST",
	      url: $(this).attr('action'), //sumbits it to the given url of the form
	      data: valuesToSubmit,
	      dataType: "JSON", // you want a difference between normal and ajax-calls, and json is standard
	      statusCode: {
		500: function(xhr) {
		  if(window.console) console.log(xhr.responseText);
		},
		201: function(xhr){
		  $("#commen_content").val("").change()
		  var message="Comentario creado"
		  //$.each(data.errors, function(key, value){
		    //message+="<br>"+value.message
		    //$("#item_"+value.field).addClass("error")
		  //})
		  $("#messageComment").removeClass("alert alert-danger").addClass("alert alert-success").html(message)
		  $('html, body').animate({
		    scrollTop: $("#messageComment").offset().top
		  }, 1000);
		  setTimeout(function(){ $("#messageComment").addClass("hidden"); }, 3000);
		},
		422: function(xhr){
		  var message="Comentario no se ha creado"
		  //$.each(data.errors, function(key, value){
		    //message+="<br>"+value.message
		    //$("#item_"+value.field).addClass("error")
		  //})
		  $("#messageComment").removeClass("alert alert-success").addClass("alert alert-danger").html(message)
		  $('html, body').animate({
		    scrollTop: $("#messageComment").offset().top
		  }, 1000);
		  setTimeout(function(){ $("#messageComment").addClass("hidden"); }, 3000);
		}, 
	      }
	  }).success(function(json){
	      console.log("success", json);
	  });
	  return false; // prevents normal behaviour
      });*/
    $(".new_comment").on("ajax:success", function(e, data, status, xhr){
      alert(status)
    }).on("ajax:error", function(e, xhr, status, error){
      var id=$(this).attr("id")
      console.log(id)
      var cmid=id.split("-")
      if(id.startsWith("micropost-")){
        console.log("Micropost")
        var message="Comentario no se ha creado"
        $("#micropostMessage-"+cmid[1]).removeClass("alert alert-success").addClass("alert alert-danger").html(message)
        $('html, body').animate({
          scrollTop: $("#micropostMessage-"+cmid[1]).offset().top
        }, 1000);
        setTimeout(function(){ $("#commentMessage-"+cmid[1]).addClass("hidden"); }, 3000);
      }
      else if(id.startsWith("comment-")){
        console.log("Comentario")
        var message="Comentario no se ha creado"
        $("#commentMessage-"+cmid[1]).removeClass("alert alert-success").addClass("alert alert-danger").html(message)
        $('html, body').animate({
          scrollTop: $("#messageComment-"+cmid[1]).offset().top
        }, 1000);
        setTimeout(function(){ $("#commentMessage-"+cmid[1]).addClass("hidden"); }, 3000);
      }
      
      console.log(e)
      console.log(xhr.status)
      console.log(status)
      console.log(error)
    })
    $('[name="show_new_comment"]').bind('ajax:success',function(evt, data, status, xhr){
      var id=$(this).attr("id");
      $("div#comment-reply-"+id).html(data);
    });
  });
</script>
<% end %>
<div class="row">
  <!-- Blog Post Content Column -->
  
  <div class="col-lg-8">
    <% if notice %>
      <div id="notice" class="alert alert-success"><%= notice %></div>
    <% end %>
    <!-- Blog Post -->
    <!-- Title -->
    <h1><%= @micropost.name %></h1>
    <!-- Author -->
    <p class="lead">
      <%= t(:micropost_user_by) %>&nbsp;<%= link_to @micropost.user, user_path(@micropost.user) %>
    </p>
    <hr>
    <!-- Date/Time -->
    <p>
      <span class="glyphicon glyphicon-time"></span> <%= t(:micropost_posted_on) %> <%= @micropost.formated_date  %>
    </p>
    <hr>
    <p>
    <%= @micropost.category %>
    </p>
    <hr>
    <!-- Preview Image -->
    <img class="img-responsive" src="http://placehold.it/900x300" alt="">
    <hr>
    <!-- Post Content -->
    <%= raw @micropost.content %>
    <!--p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat perspiciatis. Enim, iure!</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum, aliquid, animi, ut quas placeat totam sunt tempora commodi nihil ullam alias modi dicta saepe minima ab quo voluptatem obcaecati?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo, aliquam tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam recusandae? Qui, necessitatibus, est!</p-->
    <hr>
    <p>
      <%= link_to 'Edit', edit_micropost_path(@micropost) %> |
      <%= link_to 'Back', microposts_path %>
    </p>
    <hr>
    <!-- Blog Comments -->
    <!-- Comments Form -->
    <%= render :partial => '/comments/new', :micropost_id => @micropost.id %>
    <hr>
    <!-- Posted Comments -->
    <!-- Comment -->
     <%= render partial: "comment", collection: @micropost.comments %>
    <% #@micropost.comments.each do |comment| %>
    
    <% #end %>
  </div>
  
  <!-- Blog Sidebar Widgets Column -->
  <div class="col-md-4">
    <!-- Blog Search Well -->
    <div class="well">
    <h4>Blog Search</h4>
      <div class="input-group">
	<input type="text" class="form-control">
	<span class="input-group-btn">
          <button class="btn btn-default" type="button">
	    <span class="glyphicon glyphicon-search"></span>
          </button>
	</span>
      </div>
      <!-- /.input-group -->
    </div>
    <!-- Blog Categories Well -->
    <div class="well">
      <h4>Blog Categories</h4>
	<div class="row">
	  <div class="col-lg-6">
	    <ul class="list-unstyled">
	      <li>
		<a href="#">Category Name</a>
              </li>
              <li>
		<a href="#">Category Name</a>
              </li>
              <li>
		<a href="#">Category Name</a>
              </li>
	      <li>
		<a href="#">Category Name</a>
              </li>
	    </ul>
          </div>
          <div class="col-lg-6">
	    <ul class="list-unstyled">
	      <li>
		<a href="#">Category Name</a>
              </li>
              <li>
		<a href="#">Category Name</a>
              </li>
              <li>
		<a href="#">Category Name</a>
              </li>
              <li>
		<a href="#">Category Name</a>
              </li>
            </ul>
          </div>
        </div>
	<!-- /.row -->
      </div>
      <!-- Side Widget Well -->
      <div class="well">
	<h4>Side Widget Well</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
      </div>
    </div>
  </div>
  <!-- /.row -->
  <hr>
  <!-- Footer -->
  <footer>
    <div class="row">
      <div class="col-lg-12">
	<p>Copyright &copy; Your Website 2014</p>
      </div>
    </div>
    <!-- /.row -->
  </footer>